application/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('application', application, name='application'),
    path('application/category/<slug>', catapplication, name='catapplication'),
    path('application/details/<slug>', singlepageapplication, name='singlepageapplication'),

]

main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('about', about, name='about'),
    path('career', career, name='career'),
    path('contact', contact, name='contact'),
    path('dealership', dealership, name='dealership'),
    path('dvr', dvr, name='dvr'),
    path('hd/cctv', hdcctv, name='hdcctv'),
    path('hiring', hiring, name='hiring'),
    path('marketing', marketing, name='marketing'),
    path('my/account', myaccount, name='myaccount'),
    path('partner', partner, name='partner'),
    path('photo/gallery', photogallery, name='photogallery'),
    path('pro/switches', proswitches, name='proswitches'),
    path('privacy', privacy, name='privacy'),
    path('ssl', ssl, name='ssl'),
    path('user/login', userlogin, name='userlogin'),
    path('video/gallery', videogallery, name='videogallery'),
    path('support', support, name='support'),
    path('logout', logout_attempt, name='logout_attempt'),
    path('e-waste-management', waste_management, name='waste_management'),
    path('send_email', send_email, name='send_email'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('application.urls')),
    path('', include('software.urls')),
    path('', include('products.urls')),
    path('', include('adminpanel.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

software/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('software', software, name='software'),
    path('software/category/<slug>', softwarecategory, name='softwarecategory')

]

software/models.py
from django.db import models


# Create your models here.


class SoftwareCategory(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    slug = models.SlugField(max_length=300, null=True, unique=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class SoftwareSubCategory(models.Model):
    category = models.ForeignKey(SoftwareCategory, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    slug = models.SlugField(max_length=300, null=True, unique=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class SoftwareBlock(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Software(models.Model):
    category = models.ForeignKey(SoftwareSubCategory, on_delete=models.CASCADE, blank=True, null=True)
    block = models.ForeignKey(SoftwareBlock, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    model_details = models.CharField(max_length=200, blank=True, null=True)
    slug = models.SlugField(max_length=300, null=True, unique=True)
    version = models.CharField(max_length=200, blank=True, null=True)
    release_note = models.FileField(upload_to="software/release_note/")
    download = models.FileField(upload_to='software/download/')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

application/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

from application.models import *
from main.models import *
from products.models import *


# Create your views here.


def application(request):
    visit = PageVisit.objects.all().count()
    cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    app = Application.objects.all()
    pdf = PDF.objects.all()

    category = ApplicationCategory.objects.all()
    p = Paginator(app, 5)
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)
    except EmptyPage:
        page_obj = p.page(p.num_pages)
    return render(request, 'application.html',
                  {'visit': visit, 'cat': cat, 'mcat': mcat, 'page_obj': page_obj, 'category': category, 'pdf': pdf})


def catapplication(request, slug):
    visit = PageVisit.objects.all().count()
    cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    pdf = PDF.objects.all()

    category = ApplicationCategory.objects.all()
    subcat = ApplicationSubCategory.objects.get(slug=slug)
    app = Application.objects.filter(category=subcat)
    p = Paginator(app, 5)
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)
    except EmptyPage:
        page_obj = p.page(p.num_pages)
    return render(request, 'application.html',
                  {'visit': visit, 'cat': cat, 'mcat': mcat, 'page_obj': page_obj, 'category': category, 'pdf': pdf})


def singlepageapplication(request, slug):
    visit = PageVisit.objects.all().count()
    cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    pdf = PDF.objects.all()
    apps = get_object_or_404(Application, slug=slug)
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        company = request.POST.get('company')
        country = request.POST.get('country')
        state = request.POST.get('state')
        city = request.POST.get('city')
        msg = request.POST.get('msg')
        product_name = apps.name
        product_cat = apps.category.name
        data = ApplicationRequest.objects.create(name=name, email=email, company=company, country=country,
                                                 state=state, city=city, msg=msg,
                                                 application_name=product_name, application_category=product_cat)
        data.save()
        msg = "Your Contact Data Has Been Successfully Sent!"
        return render(request, 'success.html', {'msg': msg})

    return render(request, 'single-page-application.html', {'visit': visit, 'cat': cat, 'mcat': mcat, 'pdf': pdf, 'apps':apps})

main/views.py
from random import random

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse

from .models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from application.models import *
from software.models import *
from products.models import *

from django.core.mail import send_mail
from django.conf import settings


# Create your views here.


def home(request):
    cat = Category.objects.all()
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        visit = x_forwarded_for.split(',')[0]
    else:
        visit = request.META.get('REMOTE_ADDR')
    var = PageVisit.objects.create(visit=visit)
    var.save()
    visit = PageVisit.objects.all().count()
    video = EmbadedVideo.objects.all()
    products = Products.objects.all().order_by('-id')
    slider = Slider.objects.all().order_by('-id')
    mcat = MicroCategory.objects.all()
    pdf = PDF.objects.all()
    # trending = Products.objects.filter('trending').order_by('-id')[:5]
    return render(request, 'home.html', {'cat': cat, 'visit': visit, 'video': video, 'products': products,
                                         'slider': slider, 'mcat': mcat, 'pdf': pdf})


def about(request):
    visit = PageVisit.objects.all().count()
    cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    pdf = PDF.objects.all()

    return render(request, 'about.html', {'visit': visit, 'cat': cat, 'mcat': mcat, 'pdf': pdf})


def career(request):
    visit = PageVisit.objects.all().count()
    cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    pdf = PDF.objects.all()
    try:
        if request.method == 'POST':
            name = request.POST.get('name')
            surname = request.POST.get('surname')
            experience = request.POST.get('experience')
            address = request.POST.get('address')
            city = request.POST.get('city')
            field = request.POST.get('field')
            cv = request.FILES.get('cv')
            remark = request.POST.get('remark')

            data = Career.objects.create(name=name, surname=surname, experience=experience, address=address, city=city,
                                         field=field, cv=cv, remark=remark)
            data.save()
            msg = "Your Career Details Has Been Submitted!"
            subject = f"Career Details Person Name: {name} {surname} and Experience: {experience}"
            message = f"Person Name : {name}  {surname}\n Person Experience : {experience} \n Address : {address}" \
                      f" \n City Name : {city} \n Fields Name : {field}, \n Resume/CV: {settings.SITES_URL}{data.cv.url} \n Remarks {remark}"
            from_email = settings.EMAIL_HOST_USER
            recipient_list = settings.SENDING_EMAIL
            send_mail(subject, message, from_email, recipient_list)

            return render(request, 'success.html', {'msg': msg})
    except Exception as E:
        return render(request, 'success.html', {'msg': E})
    return render(request, 'career.html', {'visit': visit, 'cat': cat, 'mcat': mcat, 'pdf': pdf})


def contact(request):
    visit = PageVisit.objects.all().count()
    cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    pdf = PDF.objects.all()
    try:
        if request.method == "POST":
            name = request.POST.get('name')
            email = request.POST.get('email')
            sub = request.POST.get('sub')
            msg = request.POST.get('msg')
            data = ContactUs.objects.create(name=name, email=email, sub=sub, msg=msg)
            data.save()
            msg = "Your contact details has been sent !"
            subject = f"Contact Details Person Name: {name} and Email: {email}"
            message = f"Person Name : {name} \n Person Email : {email} \n Subject : {sub}" \
                      f" \n Messages Details : {msg} \n "
            from_email = settings.EMAIL_HOST_USER
            recipient_list = settings.SENDING_EMAIL
            send_mail(subject, message, from_email, recipient_list)
            return render(request, 'success.html', {'msg': msg})
    except Exception as E:
        return render(request, 'success.html', {'msg': E})
    return render(request, 'contact.html', {'visit': visit, 'cat': cat, 'mcat': mcat, 'pdf': pdf})


def dealership(request):
    visit = PageVisit.objects.all().count()
    cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    pdf = PDF.objects.all()

    return render(request, 'dealership.html', {'visit': visit, 'cat': cat, 'mcat': mcat, 'pdf': pdf})


def dvr(request):
    visit = PageVisit.objects.all().count()
    cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    pdf = PDF.objects.all()

    return render(request, 'dvr.html', {'visit': visit, 'cat': cat, 'mcat': mcat, 'pdf': pdf})


def hdcctv(request):
    visit = PageVisit.objects.all().count()
    cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    pdf = PDF.objects.all()

    return render(request, 'hd-cctv.html', {'visit': visit, 'cat': cat, 'mcat': mcat, 'pdf': pdf})


def hiring(request):
    visit = PageVisit.objects.all().count()
    cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    pdf = PDF.objects.all()

    return render(request, 'hiring.html', {'visit': visit, 'cat': cat, 'mcat': mcat, 'pdf': pdf})


def marketing(request):
    visit = PageVisit.objects.all().count()
    # cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    market = Marketing.objects.all()
    pdf = PDF.objects.all()

    p = Paginator(market, 12)
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)
    except EmptyPage:
        page_obj = p.page(p.num_pages)
    cat = Category.objects.all()
    return render(request, 'marketing.html',
                  {'visit': visit, 'cat': cat, 'mcat': mcat, 'page_obj': page_obj, 'pdf': pdf, 'cat': cat})


def myaccount(request):
    visit = PageVisit.objects.all().count()
    cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    pdf = PDF.objects.all()

    return render(request, 'my-account.html', {'visit': visit, 'cat': cat, 'mcat': mcat, 'pdf': pdf})


def partner(request):
    visit = PageVisit.objects.all().count()
    cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    pdf = PDF.objects.all()
    try:
        if request.method == 'POST':
            company = request.POST.get('company')
            name = request.POST.get('name')
            email = request.POST.get('email')
            password = request.POST.get('password')
            phone = request.POST.get('phone')
            website = request.POST.get('website')
            gst = request.POST.get('gst')
            year_business = request.POST.get('year_business')
            type_business = request.POST.get('type_business')
            revenue = request.POST.get('revenue')
            address = request.POST.get('address')
            city = request.POST.get('city')
            state = request.POST.get('state')
            country = request.POST.get('country')
            zipcode = request.POST.get('zipcode')
            sales_employee = request.POST.get('sales_employee')
            technical_employee = request.POST.get('technical_employee')
            major_brand = request.POST.get('major_brand')

            user_obj = User.objects.create_user(username=email, email=email, first_name=name, last_name=phone)
            user_obj.set_password(password)
            user_obj.save()

            data = Partner.objects.create(user=user_obj, company=company, name=name, email=email, phone=phone,
                                          website=website, year_business=year_business
                                          , type_business=type_business, revenue=revenue, address=address, city=city,
                                          state=state,
                                          country=country, zipcode=zipcode, sales_employee=sales_employee,
                                          technical_employee=technical_employee,
                                          major_brand=major_brand, gst=gst, password=password)
            data.save()
            msg = "Your Registrations Successfully Completed!"
            subject = f"Partnership Details Company Name: {company} and User Name: {name}"
            message = f"Person Name : {name} \n Person Email : {email} \n Person Contact Number:{phone} \n" \
                      f" Person Company Name : {company} \n Person Website Name: {website} \n Gst Details: {gst} \n" \
                      f"Business Year: {year_business} \n Types of Business: {type_business} \n Revenue: {revenue}" \
                      f" \n Person Country Name : {country} \n Person State Name: {state} \n Person City Name : {city} \n" \
                      f"Address : {revenue} \n Zip Code : {zipcode}, \n Sales Employee : {sales_employee}, \n" \
                      f"Technical Employee : {technical_employee} \n Major Brand Name : {major_brand}"
            from_email = settings.EMAIL_HOST_USER
            recipient_list = settings.SENDING_EMAIL
            send_mail(subject, message, from_email, recipient_list)
            return render(request, 'success.html', {'msg': msg})
    except Exception as E:
        return render(request, 'success.html', {'msg': E})
    return render(request, 'partner.html', {'visit': visit, 'cat': cat, 'mcat': mcat, 'pdf': pdf})


def photogallery(request):
    visit = PageVisit.objects.all().count()
    cat = Category.objects.all()
    mcat = MicroCategory.objects.all()
    gallery = GalleryCat.objects.all()
    pdf = PDF.objects.all()

    return render(request, 'photogallery.html',

main/templates/about.html
{% extends 'master.html' %}
{% load static %}
{% block content %}


<!-- <?php include 'header.php'; ?> -->

<!-- Breadcrumb Area Start -->
<div class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-content">
                    <ul class="nav">
                        <li><a href="/">Home</a></li>
                        <li>About Us</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Area End-->
<!-- About Area Start -->
<section class="about-area mtb-50px">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="about-left-image mb-md-30px mb-lm-30px ">
                    <img src="http://endroid.in/endroid-beta/beta/assets/images/slider-image/about-us.jpg" alt="" class="img-responsive rounded" />
                </div>
            </div>
            <div class="col-lg-6">
                <div class="about-content">
                    <div class="about-title">
                        <h2>Welcome To Endroid</h2>
                    </div>
                    <p class="mb-30px">
                    Endroid is a modern aged icon for security and safety. It assures the safe and secured environment for the users which ultimately results in peaceful mind. Our Smart solutions and artificial intelligence concepts provides the complete solution regarding the security and safety of our customers

                    </p>
                    <p>
                    With our cutting edge technology and deep R & D We are able to provide security products that are not only efficient but have pocket friendly prices too
                    </p>
                </div>
            </div>
        </div>
        <div class="row mt-50px">
        <div class="col-md-4">
                <div class="single-about">
                    <h4>Our Vision</h4>
                    <p>
                    We strive to become the most trusted partner in terms of quality, consistency, and up-gradation for the security services in this industry. For that tend to improve our expertise in technology and market. We strive to set the standards of encryption and safety for this rising industry in near future and make the trust of our clients our foundation.

                    </p>
                </div>
            </div>
            <div class="col-md-4 mb-lm-30px">
                <div class="single-about">
                    <h4>Our Company</h4>
                    <p>
                    Established in 2008, DBS has been working for Domestic and Commercial Security Solutions.  Within the operational period, we thrived in the security industry through top-notch research and product development, and market study.  Right now with sheer dedication, we are providing sales, & Service support to our Dealer/Distributor network .

                    </p>
                </div>
            </div>
            <div class="col-md-4 mb-lm-30px">
                <div class="single-about">
                    <h4>Our Team</h4>
                    <p>
                    we have professional sales and service team , our service team provide online support to our channel partners and hardware repair team is capable to make chip level repairing .  We have strong R and D Team and our new developed products are symbol of there success
                    </p>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- About Area End -->
<!-- <?php include 'footer.php'; ?> -->
{% endblock %}

main/templates/login.html
{% extends 'master.html' %}
{% block content %}


<!-- <?php include 'header.php'; ?> -->

    <!-- Breadcrumb Area Start -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumb-content">
                        <ul class="nav">
                            <li><a href="/">Home</a></li>
                            <li>Support Login </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Area End-->
    <!-- login area start -->
    <div class="login-register-area mb-50px mt-40px">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-12 ms-auto me-auto">
                    <div class="login-register-wrapper">
                        <div class="login-register-tab-list nav">
                            <a class="active" data-bs-toggle="tab" href="#lg1">
                                <h4>login</h4>
                            </a>
                            <!-- <a data-bs-toggle="tab" href="#lg2">
                                <h4>register</h4>
                            </a> -->
                        </div>
                        <div class="tab-content">

                            {% if user.is_support %}

                             <div id="lg1" class="tab-pane active">
                                <div class="login-form-container">
                                    <div class="login-register-form">
                                      <h5> <a href="{% url 'logout_attempt' %}">Log Out</a></h5>
                                        <br>
                                        <br>
                                       <h5><a href="{% url 'software' %}">Software</a></h5>

                                    </div>
                                </div>
                            </div>


                            {% else %}
                            <div id="lg1" class="tab-pane active">
                                <div class="login-form-container">
                                    <div class="login-register-form">
                                        <h4>{{ msg }}</h4>
                                        <form action="" method="post">
                                            {% csrf_token %}
                                            <input type="text" name="username" placeholder="Username" />
                                            <input type="password" name="password" placeholder="Password" />
                                            <div class="button-box">
                                                <div class="login-toggle-btn">
                                                    <input type="checkbox" />
                                                    <a class="flote-none" href="javascript:void(0)">Remember me</a>
                                                </div>
                                                <button type="submit"><span>Login</span></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>

                            {% endif %}

                            <div id="lg2" class="tab-pane">
                                <div class="login-form-container">
                                    <div class="login-register-form">

                                         <h4>{{ msg }}</h4>
                                        <form action="" method="post">
                                            {% csrf_token %}
                                            <input type="text" name="username" placeholder="Username" />
                                            <input type="password" name="password" placeholder="Password" />
                                            <div class="button-box">
                                                <div class="login-toggle-btn">
                                                    <input type="checkbox" />
                                                    <a class="flote-none" href="javascript:void(0)">Remember me</a>
                                                </div>
                                                <button type="submit"><span>Login</span></button>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- login area end -->
   <!-- <?php include 'footer.php'; ?> -->

{% endblock %}

main/templates/software.html
{% extends 'master.html' %}
{% block content %}


<!-- <?php include 'header.php'; ?> -->
<!-- Breadcrumb Area Start -->
<div class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-content">
                    <ul class="nav">
                        <li><a href="/">Home</a></li>
                        <li>Software</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Area End-->
<!-- Shop Category Area End -->
<div class="shop-category-area mt-30px">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 order-lg-last col-md-12 order-md-first">
                <div class="row">

                    {% for b in var %}
                    {% if b.name %}
                    <div class="col-lg-12 shadow-sm rounded py-2 my-2">
                        <h5>{{ b.name }}</h5>

                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">S.No</th>
                                    <th scope="col">Software name</th>
                                    <th scope="col">Version</th>
                                    <th scope="col">Release Note</th>
                                    <th scope="col">Download</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for v in b.software_set.all %}
                                <tr>
                                    <th scope="row">{{ v.id }}</th>
                                    <td>{{ v.name }}</td>
                                    <td>{{ v.version }} </td>
                                    {% if v.release_note %}
                                    <td><a href="{{ v.release_note.url }}" target="_blank"><i class="bi bi-file-earmark-ruled-fill text-danger"></i></td>
                                    {% endif %}
                                    {% if v.download %}
                                    <td><a href="{{ v.download.url }}" target="_blank"><i class="bi bi-file-earmark-arrow-down-fill text-danger"></i></td>
                                    {% endif %}
                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% endif %}
                    {% endfor %}


                </div>
            </div>
            <!-- Sidebar Area Start -->
            <div class="col-lg-3 order-lg-first col-md-12 order-md-last mb-md-60px mb-lm-60px">
                <div class="shop-sidebar-wrap">
                    <div class="sidebar-widget-group mt-20">
                        <h3 class="sidebar-title m-0"><span>Filter By</span></h3>
                        <!-- Sidebar single item -->
                        <div class="sidebar-widget no-cba mt-20">
                            <h4 class="pro-sidebar-title">Software Model No.</h4>
                            <form class="contact-form-style">
                                <input name="name" placeholder="Enter Model No." type="text">
                            </form>
                        </div>
                        <div class="sidebar-widget no-cba mt-20">
                            <h4 class="pro-sidebar-title">software Name</h4>
                            <form class="contact-form-style">
                                <input name="name" placeholder="Enter software Name" type="text">
                            </form>
                        </div>
                        <!-- Sidebar single item -->

                    </div>
                        <div class="sidebar-widget mb-30px">
                        <h3 class="sidebar-title"><span>Categories</span></h3>
                        <div class="accordion" id="accordionExample">

                            {% for c in category %}

                            <div class="card">
                                <div class="card-header" id="headingOne">
                                    <a href="#" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne" class="collapsed">{{ c.name }}</a>
                                </div>

                                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                                    <div class="card-body">
                                        {% for s in c.softwaresubcategory_set.all %}
                                        <ul class="category-list">
                                            <li><a href="{% url 'softwarecategory' s.slug %}">{{ s.name }}</a></li>

                                        </ul>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            {% endfor %}


                        </div>
                    </div>

                    <!-- Sidebar single item -->
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

main/templates/ssl.html
{% extends 'master.html' %}
{% block content %}


<!-- <?php include 'header.php'; ?> -->
<div class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-content">
                    <ul class="nav">
                        <li><a href="/">Home</a></li>
                        <li>SSL Certificate</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container py-5">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="py-3">SSL Certificate</h2>
        </div>
    </div>
</div>

<!-- <?php include 'footer.php'; ?> -->

{% endblock %}